### ISSUE TITLE
deleting a comment generates a popup that you have a new comment

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#68] opened 2024-10-10 17:48 UTC
Joshua writes: 
deleting a comment generates a popup that you have a new comment, but I think that'd be one case we want to ignore if it is easy?

**Comment by benloh** [comment] 2024-10-10 17:51
@jdanish Currently as of 10/10/2024 on http://rapt.inquirium.org:3000/#/ deleting a comment does not seem to generate a new status update.

**Comment by jdanish** [comment] 2024-10-10 18:15
Now I cannot reproduce it either. Closing and will re-open if I figure it out. Sorry!

**Closed by jdanish** 2024-10-10 18:15 UTC
Labels: needs replication

**Comment by benloh** [comment] 2024-10-10 18:42
I'm also having trouble reproducing the Evidence Link comment appearing in the wrong place, but I'm pretty sure I saw it earlier too.  There may have been an error condition in there somewhere, or it's also possible there's an async issue.
